# -*- mode: org; -*- 
#+TITLE: Installation of UH Thesis Layout
#+AUTHOR:Albert S. Kim
#+DATE:Tue Dec  4 03:12:26 HST 2018      
#+HTML_HEAD_EXTRA: <link rel=alternate stylesheet type=text/css href=style2.css />
#+HTML_HEAD: <link rel=stylesheet href=http://dakrone.github.io/org.css type=text/css />
#+HTML_HEAD: <style type=text/css>body{ max-width:100%; }</style>
#+STARTUP: indent  
#+LATEX_HEADER: \usepackage[margin=1.0in]{geometry} 
#+LATEX_HEADER: \usepackage[numbers,sort&compress,square]{natbib}
#+latex_header: \usepackage{glossaries}
#+latex_header: \makeglossaries
#+OPTIONS: d:nil ^:nil H:2 toc:nil

* Installation guide of UHM thesis lyx laytout.

** Installation procedure
In Ubuntu, execute the following commands in terminal:
#+begin_src bash :results output  
sudo mkdir               /usr/share/texmf/tex/latex/uhthesis
sudo cp uhthesis.cls     /usr/share/texmf/tex/latex/uhthesis/
sudo cp uhthesis.lyaout  /usr/share/lyx/layouts
sudo texhash 
#+end_src
#
In Mac, execute the following commands in terminal:
#+begin_src bash :results output  
/usr/local/texlive/2017/texmf-dist/tex/latex
/Applications/LyX.app/Contents/Resources/layouts
#+end_src
#
** Lyx reconfigure
1. Open Lyx, go to  "Tools" and click "Reconfigure". And, restart Lyx.
2. Open uhthesis.lyx and delete: ERT: %\bibliographystyle{plain}
3. bibliography
   a. Go to Document → Settings.
   b. Click Bibliography
   c. Select "Natbib" for Style format  and "Author-number" for Varient.
   d. Input "sort&compress" in Options
   e. Click "OK" to save and exit.
   f. Go to Insert (in the main menu) → LIST/TOC → Bibliography.
   g. Open the Bibiliography and select your bibliography file in Database.
   h. Select "elsarticle-num-cepl" in Style 
4. Insert citations and click view (an icon of eyes).


** References
- http://blog.anidear.com/2011/03/lyx-convert-latex-cls-file-to-layout-in.html

